### ISSUE TITLE
NO EMAIL 

### ISSUE THREAD

**Issue by HRLiao** [omekeki/blog_issue_tracker#11]
hi ur site succ ik krijg geen email van de registratie NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOB

**Comment by omekeki** [comment]
Please refrain from posting issues this way next time.

**Comment by omekeki** [comment]
*Fixed
