### ISSUE TITLE
Menu text

### ISSUE THREAD

**Issue by Ldebruine97** [omekeki/blog_issue_tracker#8]

**Comment by Ldebruine97** [comment]
![no_caps](https://cloud.githubusercontent.com/assets/15999138/22159308/96d707a8-df83-11e6-9ab9-4bfb1841e2da.png)
![no_caps2](https://cloud.githubusercontent.com/assets/15999138/22159313/9e304186-df83-11e6-984c-724823f294a1.png)
Text in menu has no capitalized letters after login, is fixed after reloading the page though.

**Comment by omekeki** [comment]
*Fixed.
